language: node_js
node_js:
- '0.11'
- '0.10'

script: true

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: visualiza.tideapps.com
  skip_cleanup: true
  upload-dir: test
  local_dir: tests3
