language: node_js
node_js:
- '0.11'
- '0.10'


deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS SECRET
  bucket: visualiza.tideapps.com
  skip_cleanup: true
  upload-dir: test